#!/usr/bin/expect -f
#  ./ssh.exp password 192.168.1.11 id
set pass [lrange $argv 0 0]
set server [lrange $argv 1 1]
set name [lrange $argv 2 2]
set port [lrange $argv 3 3]

spawn ssh $name@$server -p $port
match_max 100000
expect "*?assword:*"
send -- "$pass\r"
interact
